# Generated by Django 4.2.7 on 2023-11-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('hobbies', models.TextField()),
                ('favorite_music', models.TextField()),
                ('favorite_food', models.TextField()),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
