# Generated by Django 4.2.7 on 2023-11-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_login_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login',
            field=models.CharField(max_length=255),
        ),
    ]
